artifact_location: file:///home/runner/work/Workflow-CI/Workflow-CI/MLProject/mlruns/0
creation_time: 1759856051803
experiment_id: '0'
last_update_time: 1759856051803
lifecycle_stage: active
name: Default
