name: MLflow CI Workflow

on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MLflow and dependencies
        run: pip install mlflow scikit-learn pandas

      - name: Run MLflow Project
        run: mlflow run ./MLProject

      # Bagian ini untuk memenuhi Level Skilled (3 Poin)
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifact
          path: |
            MLProject/mlruns/
