name: MLflow CI Workflow

on:
  push:
    branches:
      - main

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install mlflow==2.9.2 scikit-learn==1.3.2 pandas==2.1.1

      - name: Run Python Training Script
        working-directory: ./MLProject
        run: python modelling.py
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- PERUBAHAN DI SINI ---
      # Build image dari Dockerfile tanpa build-arg
      - name: Build and push Docker image from Dockerfile
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/workflow-ci-model:latest"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
      # --- SELESAI PERUBAHAN ---
      
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifact
          path: MLProject/mlruns/