name: MLflow CI Workflow

on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # --- PERUBAHAN DI SINI: INSTAL SEMUA DALAM SATU LANGKAH ---
      - name: Install all dependencies
        run: pip install mlflow==2.9.2 scikit-learn==1.3.2 pandas==2.1.1 docker "urllib3<2.0"

      - name: Run Python Training Script
        working-directory: ./MLProject
        run: python modelling.py

      # Setup environment Docker
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        working-directory: ./MLProject
        env:
          DOCKER_HOST: "unix:///var/run/docker.sock"
        run: |
          RUN_ID=$(cat run_id.txt)
          mlflow models build-docker \
            --model-uri "runs:/$RUN_ID/model" \
            --name "${{ secrets.DOCKERHUB_USERNAME }}/workflow-ci-model"

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/workflow-ci-model

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifact
          path: MLProject/mlruns/
