name: MLflow CI Workflow

on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # --- PERUBAHAN DI SINI ---
      # Kita instal semua dependensi secara manual
      - name: Install dependencies
        run: pip install mlflow==2.9.2 scikit-learn==1.3.2 pandas==2.1.1

      # --- PERUBAHAN DI SINI ---
      # Kita jalankan MLflow tanpa membuat environment Conda
      - name: Run MLflow Project
        run: mlflow run ./MLProject --no-conda

      # Bagian ini untuk arsip artefak
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifact
          path: |
            MLProject/mlruns/
