name: MLflow CI Workflow

on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install mlflow==2.9.2 scikit-learn==1.3.2 pandas==2.1.1

      - name: Run MLflow Project
        working-directory: ./MLProject
        run: mlflow run . --env-manager=local

      # --- BAGIAN BARU UNTUK DOCKER ---
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Read MLflow Run ID
        id: read_run_id
        run: echo "RUN_ID=$(cat MLProject/run_id.txt)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          mlflow models build-docker \
            --model-uri "runs:/${{ steps.read_run_id.outputs.RUN_ID }}/model" \
            --name "${{ secrets.DOCKERHUB_USERNAME }}/workflow-ci-model"

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/workflow-ci-model
      # --- SELESAI BAGIAN BARU ---
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifact
          path: MLProject/mlruns/
